/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import javax.swing.table.*;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author divyam
 */
public class check extends javax.swing.JFrame {
    int xmouse;
    int ymouse;

    /**
     * Creates new form check
     */
    public check() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Statement stmt=null;
ResultSet rs=null;
String sql="Select * from student ";
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        framedrag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(925, 640));
        setMinimumSize(new java.awt.Dimension(925, 640));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NAME", "ID", "ADDRESS", "CITY", "PHONENO", "EMAIL                        ", "DAYS", " ROOM", "TOTALAMOUNT"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(155);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 200, 920, 310);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 160, 220, 40);

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(870, 0, 50, 40);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(730, 160, 90, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 520, 100, 30);

        txtid.setOpaque(false);
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid);
        txtid.setBounds(140, 520, 160, 30);

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel6MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 160, 130, 40);

        txtsearch.setOpaque(false);
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtsearch);
        txtsearch.setBounds(150, 170, 170, 30);

        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(810, 0, 40, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/dVM 6.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 930, 640);

        jLabel8.setText("jLabel8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1, 0, 40, 40);

        framedrag.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        framedrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                framedragMousePressed(evt);
            }
        });
        framedrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                framedragMouseDragged(evt);
            }
        });
        getContentPane().add(framedrag);
        framedrag.setBounds(0, 0, 920, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
int rows = model.getRowCount();
if(rows>0)
{
    for(int i=0;i<rows;i++)
        model.removeRow(0);
}
String query="select * from dvm";
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
             Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost/test");
              Statement stmt= con.createStatement();
              
              ResultSet rs = stmt.executeQuery(query);

            while (rs.next()){

             String NAME = rs.getString("name");
             String ID = rs.getString("id");
             String ADDRESS = rs.getString("address");
             String CITY = rs.getString("city");
             String PHONENO = rs.getString("phone");
             String EMAIL = rs.getString("email");
             int DAYS = rs.getInt("days");
             int ROOM = rs.getInt("room");
             int TOTALAMOUNT = rs.getInt("amt");
             System.out.println(NAME+"|"+ID+"|"+ADDRESS+"|"+CITY+"|"+PHONENO+"|"+EMAIL+"|"+DAYS+"|"+ROOM+"|"+TOTALAMOUNT);
model.addRow (new Object[] {NAME,ID,ADDRESS,CITY,PHONENO,EMAIL,DAYS,ROOM,TOTALAMOUNT});
            }
        }
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseReleased

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
WELCOME n2=new WELCOME();
n2.setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseReleased

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        try {
 Class.forName("com.mysql.jdbc.Driver");
 Connection con = (Connection)
 DriverManager.getConnection("jdbc:mysql://localhost:3306/test");
 Statement stmt=null;
 ResultSet rs=null;
 stmt=con.createStatement();
 String id=txtid.getText();
 String strSQL="delete from dvm where id = '"+(id)+"'";
   int rowsEffected = stmt.executeUpdate(strSQL);
   if (rowsEffected == 0)
   {
         JOptionPane.showMessageDialog(this, "record does not exist");
   }
   else
   {
           JOptionPane.showMessageDialog(this, "record deleted");
           System.out.println(rowsEffected + " rows effected");
   }
        }
        catch(Exception e) 
  {
      JOptionPane.showMessageDialog(this,e.getMessage());
      e.printStackTrace();
  }
    

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased

    String search;
    search=txtsearch.getText();
   
   final Object[] columnNames=new String[] {"NAME","ID","ADDRESS","CITY", "PHONENO","EMAIL","DAYS","ROOM","TOTALAMOUNT"};
        
        DefaultTableModel dtm=new DefaultTableModel(columnNames,0);
    String sql1="select * from dvm";
    
    try
    {

     Class.forName("com.mysql.jdbc.Driver");
        Connection con = (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/test") ;
        stmt=con.createStatement();
        rs=stmt.executeQuery(sql1);
        rs.first();
        int i=0;
        String n=rs.getString("name");
        if( n.equals(search))
        {
             String name=rs.getString("name");
            String id=rs.getString("id");
            String address=rs.getString("address");
            String city=rs.getString("city");
            String phone=rs.getString("phone");
            String email=rs.getString("email");
            String days=rs.getString("days");
            String room=rs.getString("room");
            String amt=rs.getString("amt");
            
            dtm.addRow(columnNames);
            dtm.setValueAt(name, i, 0);
            dtm.setValueAt(id, i, 1);
            dtm.setValueAt(address, i, 2);
            dtm.setValueAt(city, i, 3);
            dtm.setValueAt(phone, i, 4);
            dtm.setValueAt(email, i, 5);
             dtm.setValueAt(days, i, 6);
              dtm.setValueAt(room, i, 7);
               dtm.setValueAt(amt, i, 8);
           
            JOptionPane.showMessageDialog(this, id+address+city+phone+email+days+room+amt);
            i++;
           
        }
        
        else
        {
            JOptionPane.showMessageDialog(this, "hello");
            
            while(rs.next())
            {
                n=rs.getString("name");
                if( n.equals(search))
                { 
                    String name=rs.getString("name");  
                 String id=rs.getString("id");
            String address=rs.getString("address");
            String city=rs.getString("city");
            String phone=rs.getString("phone");
            String email=rs.getString("email");
            String days=rs.getString("days");
            String room=rs.getString("room");
            String amt=rs.getString("amt");
            
           
             dtm.addRow(columnNames);
            dtm.setValueAt(name, i, 0);
            dtm.setValueAt(id, i, 1);
            dtm.setValueAt(address, i, 2);
            dtm.setValueAt(city, i, 3);
            dtm.setValueAt(phone, i, 4);
            dtm.setValueAt(email, i, 5);
             dtm.setValueAt(days, i, 6);
              dtm.setValueAt(room, i, 7);
               dtm.setValueAt(amt, i, 8);
            
            i++;
                    
                }
            }
        }
        jTable1.setModel(dtm);
        
    }


catch(Exception e)
    
{
    JOptionPane.showMessageDialog(this, e);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseReleased

    private void framedragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMousePressed

        xmouse=evt.getX();
        ymouse=evt.getY();
        // TODO add your handling code here:
    }//GEN-LAST:event_framedragMousePressed

    private void framedragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_framedragMouseDragged
        int x =evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse,y-ymouse);
        // TODO add your handling code here:
    }//GEN-LAST:event_framedragMouseDragged

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.setState(check.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
WELCOME n2=new WELCOME();
n2.setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new check().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel framedrag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
